### ISSUE TITLE
Sonarr "Week" Calendar not fitting episodes

### ISSUE THREAD

**Issue by DFDC** [iFelix18/Darkerr#1]
Thanks for putting this together!

There's a bit of overflow for the table that shows the weekly calendar. Can't test it compared to Radarr since it lacks the weeks view and I've confirmed the other calendar layouts are fine/working as intended.

![image](https://cloud.githubusercontent.com/assets/16169356/26185357/0feecc3e-3b50-11e7-88ac-c5f16f0726a3.png)

**Comment by DFDC** [comment]
Weird, if I click off of it and back in it works fine.

**Comment by iFelix18** [comment]
I have no problems, and I cannot reproduce it.
Withoutot style is everything ok?

**Comment by DFDC** [comment]
Actually, good point. It still happens with the style off. My bad.
Any chance of changing the highlighted/current day to a darker color?

**Comment by iFelix18** [comment]
> Any chance of changing the highlighted/current day to a darker color?

With the upcoming update, which I'm working on
