### ISSUE TITLE
Drop down not showing correctly when adding a new series

### ISSUE THREAD

**Issue by arogl** [iFelix18/Darkerr#12]
![addnewseries-sonarr](https://user-images.githubusercontent.com/1115472/45923269-131a8380-bf25-11e8-86e1-8690198c2cc0.jpeg)

Sonarr Version    3.0.0.260
Darkerr Version   3.0.0-beta3

The dropdown for changing the default directory is not correctly coloured, as seen in attached.

**Comment by iFelix18** [comment]
Try 3.0.0-beta4, it should be ok now. Let me know.

**Comment by arogl** [comment]
Just tested and working.

Thanks for the update.
