### ISSUE TITLE
File browser dropdown in edit show not sytled

### ISSUE THREAD

**Issue by arogl** [iFelix18/Darkerr#14]
![file browser](https://user-images.githubusercontent.com/1115472/46898590-e1fef480-cecd-11e8-9218-a6984d7413c5.JPG)

Browser: FF Nightly
Version:    3.0.0.266
Darkerr:    3.0.0-beta5

**Comment by iFelix18** [comment]
Thanks, try beta6

**Comment by arogl** [comment]
Tested and working, Thanks.
