### ISSUE TITLE
Sonarr v3 Cards/Tiles are Bright White

### ISSUE THREAD

**Issue by jasonmdyess** [iFelix18/Darkerr#15]
Love having a dark theme. I had hoped Sonarr V3 would have one embedded, but no joy. glad I found yours though. It works great with the current version of Radarr. On Sonarr V3 (currently alpha) though, all of the inset tiles and pop-up cards are white. They did a complete redesign of the UI and it looks like the CSS names need to be updated.I have no idea what the new values should be (or much of anything about CSS), but a full text search of the source files for V3 and V2 shows that they are no longer using, for example, .thingy or .add-thingy.

Pictures below (not exhaustive).

Again, thank you so much for making this.

![image](https://user-images.githubusercontent.com/29062879/52186294-18011500-27ec-11e9-9070-1ef8926775db.png)
![image](https://user-images.githubusercontent.com/29062879/52186314-39620100-27ec-11e9-8b5b-67f84f82c0ce.png)
![image](https://user-images.githubusercontent.com/29062879/52186325-54347580-27ec-11e9-8afe-0d5053e259fa.png)
![image](https://user-images.githubusercontent.com/29062879/52186344-74fccb00-27ec-11e9-9983-83371397af25.png)

**Comment by arogl** [comment]
There are updated styles in the develop branch that have been working well on Sonarr v# for myself for some time now.

**Comment by iFelix18** [comment]
Currently, Sonarr V3 and Lidarr are supported by the theme in the [develop branch](https://github.com/iFelix18/Darkerr/tree/develop), Radarr from the [master branch](https://github.com/iFelix18/Darkerr/tree/master).

The installation is done in the same way, see the READMEs.
