### ISSUE TITLE
White popups

### ISSUE THREAD

**Issue by arogl** [iFelix18/Darkerr#18]
When I hover over the downloaded file info in activity while it is waiting, the popup is white with white text

![image](https://user-images.githubusercontent.com/1115472/56540068-01788780-65ab-11e9-8d2f-62a15088e8e6.png)

Popups on the calendar screen is white with black text, e.g. Season fianle

I am running 
Darkerr 3.0.0-beta8 
Sonarr 3.0.1.449
Firefox NIghtly 68.0a1 (2019-04-22) (64-bit)

**Comment by iFelix18** [comment]
Try 3.0.0-beta9

**Comment by arogl** [comment]
beta9 has fixed the issue.

Thanks for the quick response.
