### ISSUE TITLE
Can't get theme to work with reverse proxy

### ISSUE THREAD

**Issue by akanealw** [iFelix18/Darkerr#3]
I installed the theme using Tampermonkey and can't get the theme to work with my reverse proxy. I added in a "/" in "RegExp("^((http(s?))://)?[-A-Za-z0-9+&@#/%?=~_|!:,.;/]+(8989|7878|radarr|sonarr)+(.*)$")).test(document.location.href))" but it still didn't work. I don't really know regex so I'm not sure what else to try. 

Thanks!

**Comment by iFelix18** [comment]
I quote the [answer](https://www.reddit.com/r/sonarr/comments/6co7h3/darkerr_update/dhxfand/) given on Reddit:

> From what address you connect to Sonarr and Radarr?
> 
> Type
> ```
> // @include Your_Sonarr_url_here/*
> // @include Your_Radarr_url_here/*
> ```
> before to
> ` // ==/UserScript==
> `
> Delete
> `if (false || (new RegExp("^((http(s?))://)?[-A-Za-z0-9+&@#/%?=~_|!:,.;]+(8989|7878|radarr|sonarr)+(.*)$")).test(document.location.href))`
> 
> It should work, let me know.
> However, I recommend installing the theme through [Stylus](http://add0n.com/stylus.html).

**Comment by akanealw** [comment]
I wasn't able to get it working via Tampermonkey, but with Stylus it worked immediately. Thanks for your help.
