### ISSUE TITLE
[Solution] Server Side Installation (with nginx)

### ISSUE THREAD

**Issue by leram84** [iFelix18/Darkerr#6]
Figured i should just leave this here. If anyone wants to install this server side so you dont need an extension or anything, it's possible if you are using a webserver (though i've only tested this with nginx, it should work anywhere). Add these lines to your sonarr/radarr location blocks in nginx.conf:

```
        proxy_set_header Accept-Encoding "";
        sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="//rawgit.com/iFelix18/Darkerr/master/darkerr.css"></head>';
        sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="//rawgit.com/iFelix18/Darkerr/master/logo_animation.css"></head>';
        sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="//rawgit.com/iFelix18/Darkerr/master/hidden_searchbar.css"></head>';
        sub_filter_once on;
```

Restart nginx and you should be good to go :)

(might be useful to add this to the readme)

**Comment by iFelix18** [comment]
Thanks for the solution, added it to the readme.

**Comment by mouzzampk2014** [comment]
I know its a year old issue. I am very new to dockers and need your super help to install this on dockers. My file nginx.conf doesn't have any radar or sonar blocks. I have .docker/config/letsencrypt/nginx/nginx.conf

Is there anything I need to do?

Complete noob :(

**Comment by iFelix18** [comment]
Look into wikis on how to create the block for [Sonarr](https://github.com/Sonarr/Sonarr/wiki/Reverse-Proxy) and [Radarr](https://github.com/Radarr/Radarr/wiki/Reverse-Proxy).
