### ISSUE TITLE
Outstanding Items

### ISSUE THREAD

**Issue by ydkmlt84** [iFelix18/Darkerr#7]
If I have found a few outstanding items, i.e. whitewashed backgrounds, would you rather a pull request or just raise an issue for them?
![Example](https://i.imgur.com/AHCsjUa.png)

**Comment by iFelix18** [comment]
Sorry for the delay in the reply... yes, a pull request and any help is welcome, thanks.

**Comment by ydkmlt84** [comment]
Awesome. I’ll work on this later on. Anything else you’d like help with? Specifically anyways?

**Comment by iFelix18** [comment]
Nothing specifically, but thanks.

**Comment by iFelix18** [comment]
I saw that there were other problems, especially with Radarr, so I made several changes... there is a new version in the "develop" branch, if you want, you can take a look and tell me if you find any problems.

**Comment by ydkmlt84** [comment]
Awesome. I will take a look this afternoon. Thanks.

**Comment by kjac3585** [comment]
You might have already addressed this, but the black text on the dark grey background (e.g. the search bar) is really hard to read as well.

**Comment by iFelix18** [comment]
New update in the develop branch, let me know if there's anything else to fix.

**Comment by ydkmlt84** [comment]
Looks good to me. Thanks for the work you've put in on this.

**Comment by iFelix18** [comment]
Thanks @ydkmlt84 

Another update in the develop branch...  I fix a button, the mobile view, and I changed the color of the movies/series/episodes titles (is more readable, I think).

For me it's all right now, soon should be in the master branch.

**Comment by iFelix18** [comment]
The master branch has been updated
